---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# pexpec

<!-- badges: start -->

<!-- badges: end -->

The partial expectation of a random variable $X$ over $\mathcal{A}$ is:

$$
\mathbb{E}(X^k \ \mathbb{I}\{X \in \mathcal{A}\})
$$

A special case is when $k \in \{1,2\}$ and $\mathcal{A}$ is either $X \leq x$ or $X \geq x$. This package provides simple computations of this partial expectations for some parametric distribution models

-   Normal.

-   Log-Normal.

-   Exponential

-   Beta.

-   Gamma.

-   Weibull.

-   Binomial.

-   Negative Binomial.

-   Hypergeometric.

-   Poisson.

This partial expectations often arise when calculated expected values or variance of truncated or split linear functions of the original variables.

## Installation

Alpha version of 0.9 published with functions for all the distributions listed above. The functions are still under testing. You can install `pexpec` like so:

``` r
library(devtools)
devtools::install_git('pcosatto/pexpec')
```

Please submit any comments, errors or suggestions to pcosatto\@fi.uba.ar.
